version: "3.8"

services:

#  db:
#    container_name: mydb
#    build: ./docker/mysql
#    restart: always
#    tty: true
#    environment:
#      MYSQL_DATABASE: mydb
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_ROOT_HOST: '%'
#    expose:
#      - '3306'
#    ports:
#      - "3306:3306"
#    volumes:
#      - ./docker/mysql/conf.d:/etc/mysql/conf.d
#      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
#    networks:
#      - local-net
#    command: >
#      bash -c "sleep 5 && mysql -uroot -proot mydb < /docker-entrypoint-initdb.d/init.sql"


  api:
    container_name: 'api'
    build: ./docker/api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - local-net
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 1G
networks:
  local-net:
    driver: bridge


